global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ml-consumer"
    static_configs:
      - targets: ["realtime-consumer:8001"]

  - job_name: "ml-tailer"
    static_configs:
      - targets: ["realtime-tailer:8002"]